### ISSUE TITLE
Add "Edit" button to each page

### ISSUE THREAD

**Issue by FoggyFinder** [AvaloniaCommunity/Avalonia.FuncUI.Docs#6]
It would be nice to have ability to edit source of the document in case one find there a typo or something like that.

Samples:

![sample1](https://user-images.githubusercontent.com/16510738/80861353-c35e7b00-8c76-11ea-91d4-689f06b5ba50.jpg)

![sample2](https://user-images.githubusercontent.com/16510738/80861360-c6f20200-8c76-11ea-9dbb-768bfeaeee17.jpg)

Screenshots are taken from https://docs.microsoft.com and https://lvcharts.net

**Comment by AngelMunoz** [comment]
thanks to @NicoVIII for providing this this, please give it a try and let us know if that works or how can we improve it further

**Comment by FoggyFinder** [comment]
Awesome :-) Works perfectly
