### ISSUE TITLE
Border.borderthickness doesn't work the way the Docs show

### ISSUE THREAD

**Issue by NicoVIII** [AvaloniaCommunity/Avalonia.FuncUI.Docs#7]
As far as I could see using the current version of FuncUI (0.4) and Avalonia (0.9.9) the lines
```
Border.borderThickness 2.0 5.0
..
Border.borderThickness 1.0 2.0 3.0 4.0
```
did not work for me. The overloads of borderThickness allow only float or Thickness as parameter.

Is this an error in the docs? I'm not entirely sure, that's why I didn't open an PR...

**Comment by FoggyFinder** [comment]
It does look like an error in the docs. The right way is

```fsharp
Border.borderThickness (2.0, 5.0)
..
Border.borderThickness (1.0, 2.0, 3.0, 4.0)
```

**Comment by NicoVIII** [comment]
Thank you! I used the Thickness constructor and didn't try it directly with the tuples.

I'll open a PR for that.

**Comment by AngelMunoz** [comment]
I completely overlooked that thank you!
