### ISSUE TITLE
[Suggestion] Use GitHub Action to automatically deploy docs

### ISSUE THREAD

**Issue by NicoVIII** [AvaloniaCommunity/Avalonia.FuncUI.Docs#9]
If I'm not wrong you're using GitHub Pages to host the docs.

Wouldn't it be an option to use GitHub Actions to automatically build the HTML and deploy it to GitHub Pages? Then you wouldn't have to tidy up behind PRs (like mine... :D) and you wouldn't have the generated code inside the regular branches.

I saw this approach here and quite liked it:
https://github.com/Krzysztof-Cieslak/SampleWaypoint/blob/master/.github/workflows/docs.yml

You could change the trigger e.g. to:
```
on:
  push:
    branches:
      - master
```

What do you think? Are there reasons to not use this approach?

**Comment by AngelMunoz** [comment]
this would be a nice addition, I did want to go for this when I made the initial setup, but I didn't have the time for it, If you want to give a try for this I wouldn't mind ;)

I appreciate a lot the other contributions you have been doing so far! it really helps

**Comment by AngelMunoz** [comment]
once again thank you very much! we now have automated docs deployments! this simplifies a lot :) I'll update the readme to reflect this lovely change, thank you!

**Comment by AngelMunoz** [comment]
Oh silly me, I forgot you have updated it already in your PR I don't know why I'm so distracted today :)

**Comment by NicoVIII** [comment]
Happens to everyone, I guess :D
